theme: jekyll-theme-cayman
title: 'f7t4jhub: FirecREST for JupyterHub Helm Chart'
subtitle: 'This is a repository for a Helm chart to deploy JupyterHub using the [firecrestspawner](https://github.com/eth-cscs/firecrestspawner)'
