apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Release.Name }}-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-common-secrets
    creationPolicy: Owner
  data:
  - secretKey: kc_client_secret
    remoteRef:
      key: {{ .Values.vault.secretPath }}
      property: kc_client_secret
  - secretKey: kc_client_id
    remoteRef:
      key: {{ .Values.vault.secretPath }}
      property: kc_client_id
