apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secret
type: Opaque
stringData:
    firecrest-url: {{ .Values.setup.firecrest_url }}
    auth-token-url: {{ .Values.setup.auth_token_url}}
