apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
spec:
  commonName: {{ .Values.config.commonName }}
  dnsNames:
  - {{ .Values.config.commonName }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: {{ .Release.Name }}-cert-secret
