apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
spec:
  commonName: {{ index .Values.config.commonNames 0 }}
  dnsNames:
  {{- range .Values.config.commonNames }}
  - {{ . }}
  {{- end }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http01
  secretName: {{ .Release.Name }}-cert-secret
