apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: {{ .Values.proxy.image }}
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        command:
          - "configurable-http-proxy"
          - "--ip=0.0.0.0"
          - "--port={{ .Values.network.appPort }}"
          - "--default-target=http://{{ .Release.Name }}-hub-svc:{{ .Values.network.externalPort }}"
          - "--api-ip=0.0.0.0"
          - "--api-port={{ .Values.network.apiPort }}"
          # - "--error-target http://10.42.8.16:{{ .Values.network.externalPort }}/hub/error"
          # - "--log-level info"
        ports:
        - containerPort: {{ .Values.network.appPort }}
        env:
          {{- if .Values.vault.configProxyAuthToken.enabled }}
          - name: CONFIGPROXY_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-common-secrets
                key: configProxyAuthToken
          {{- else }}
          - name: CONFIGPROXY_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: configProxyAuthToken
          {{- end }}
