apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hub
  labels:
    app: hub
  annotations:
    {{- if .Values.reloader.enabled }}
    configmap.reloader.stakater.com/reload: "{{ .Release.Name }}-configmap"
    secret.reloader.stakater.com/reload: "{{ .Release.Name }}-common-secrets"
    {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hub
  template:
    metadata:
      labels:
        app: hub
      annotations:
      {{- if .Values.metricbeat.enabled }}
        co.elastic.metrics/enabled: "true"
        co.elastic.metrics/hosts: '"${data.host}:{{ .Values.network.externalPort }}"'
        co.elastic.metrics/metrics_path: /metrics
        co.elastic.metrics/metricsets: collector
        co.elastic.metrics/module: prometheus
      {{- end }}
    spec:
      securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          fsGroup: 1000
      containers:
      - name: hub
        image: {{ .Values.hub.image }}
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        command:
          - "/bin/bash"
          - "-c"
          - >
              . /opt/jhub-env/bin/activate &&
              jupyterhub --config /etc/config/jupyterhub_config.py --ip 0.0.0.0
              {{- if .Values.hub.debug }} --debug{{- end }}
        ports:
        - containerPort: {{ .Values.network.appPort }}
        env:
          - name: FIRECREST_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: firecrestUrl
          - name: AUTH_TOKEN_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: authTokenUrl
          - name: SA_AUTH_TOKEN_URL
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: serviceAccountAuthTokenUrl
          {{- if .Values.vault.keycloak.enabled }}
          - name: KC_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-common-secrets
                key: kc_client_id
          - name: KC_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-common-secrets
                key: kc_client_secret
          - name: SA_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-common-secrets
                key: sa_client_id
          - name: SA_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-common-secrets
                key: sa_client_secret
          {{- end }}
          {{- if .Values.vault.configProxyAuthToken.enabled }}
          - name: CONFIGPROXY_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-common-secrets
                key: configProxyAuthToken
          {{- else }}
          - name: CONFIGPROXY_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-secret
                key: configProxyAuthToken
          {{- end }}
        volumeMounts:
          - name: db-pvc
            mountPath: /home/juhu
          - name: jupyterhub-config
            mountPath: /etc/config
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
        - name: db-pvc
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
        - name: jupyterhub-config
          configMap:
            name: {{ .Release.Name }}-configmap
            items:
              - key: jupyterhub-config
                path: jupyterhub_config.py
      {{- if .Values.vault.containerRegistry.enabled }}
      imagePullSecrets:
      - name: {{ .Release.Name }}-registry-docker-config
      {{- end }}
