{{- if or .Values.vault.keycloak.enabled .Values.vault.configProxyAuthToken.secretPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-external-secret
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Release.Name }}-secret-store
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-common-secrets
    creationPolicy: Owner
  data:
  - secretKey: kc_client_secret
    remoteRef:
      key: {{ .Values.vault.keycloak.secretPath }}
      property: kc_client_secret
  - secretKey: kc_client_id
    remoteRef:
      key: {{ .Values.vault.keycloak.secretPath }}
      property: kc_client_id
  - secretKey: configProxyAuthToken
    remoteRef:
      key: {{ .Values.vault.configProxyAuthToken.secretPath }}
      property: config_proxy_auth_token
  - secretKey: sa_client_id
    remoteRef:
      key: {{ .Values.vault.keycloak.secretPath }}
      property: sa_client_id
  - secretKey: sa_client_secret
    remoteRef:
      key: {{ .Values.vault.keycloak.secretPath }}
      property: sa_client_secret
{{- end }}
