apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-proxy-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
  {{- range $issuer, $config := .Values.config.certificates }}
    {{- range $config.urls }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}-proxy-svc
            port:
              number: {{ $.Values.network.appPort }}
      - path: /hub/api
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}-proxy-svc
            port:
              number: {{ $.Values.network.appPort }}
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}-proxy-svc
            port:
              number: {{ $.Values.network.apiPort }}
    {{- end }}
  {{- end }}
  tls:
    {{- range $issuer, $config := .Values.config.certificates }}
    {{- range $config.urls }}
    - hosts:
      - {{ . }}
      secretName: {{ $.Release.Name }}-cert-{{ $issuer }}-secret
    {{- end }}
    {{- end }}
