apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-proxy-ingress
  annotations:
    {{- if .Values.metricbeat.deny_metrics_endpoint }}
    nginx.ingress.kubernetes.io/server-snippet: |
      location /hub/metrics {
        deny all;
      }
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
  {{- range .Values.config.commonNames }}
  - host: {{ . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}-proxy-svc
            port:
              number: {{ $.Values.network.appPort }}
      - path: /hub/api
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}-proxy-svc
            port:
              number: {{ $.Values.network.appPort }}
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ $.Release.Name }}-proxy-svc
            port:
              number: {{ $.Values.network.apiPort }}
  {{- end }}
  tls:
  - hosts:
    {{- range .Values.config.commonNames }}
    - {{ . }}
    {{- end }}
    secretName: {{ .Release.Name }}-cert-secret
