apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-secret
type: Opaque
stringData:
    firecrestUrl: {{ .Values.setup.firecrestUrl }}
    authTokenUrl: {{ .Values.setup.authTokenUrl}}
    configproxyAuthToken: '4558b4fda13ade6c8374037f1d18e9ce1465dded' 
