{{- if .Values.vault.keycloak.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ .Release.Name }}-secret-store
spec:
  provider:
    vault:
      server: {{ .Values.vault.url }}
      path: {{ .Values.vault.secretEngine }}
      version: "v2"
      auth:
        appRole:
          path: "approle_k8s"
          roleId: {{ .Values.vault.roleId }}
          secretRef:
            name: "vault-approle-secret"
            key: "secret-id"
{{- end }}
