apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hub-svc
spec:
  selector:
    app: hub
  type: ClusterIP
  ports:
    - name: external
      port: {{ .Values.network.externalPort }}
      targetPort: {{ .Values.network.externalPort }}
