apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-proxy-svc
spec:
  selector:
    app: proxy
  type: ClusterIP
  ports:
    - name: app
      port: {{ .Values.network.appPort }}
      targetPort: {{ .Values.network.appPort }}
    - name: api
      port: {{ .Values.network.apiPort }}
      targetPort: {{ .Values.network.apiPort }}
    - name: external
      port: {{ .Values.network.externalPort }}
      targetPort: {{ .Values.network.externalPort }}
