name: Kubesec

on:
  push:
    branches: [ "main", "gh-pages" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '40 5 * * 2'

jobs:
  lint:
    name: Kubesec
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Render chart into a single yaml file
      - name: Render Helm chart
        run: |
          helm template chart/ > rendered.yaml

      - name: Run Kubesec scanner
        uses: controlplaneio/kubesec-action@43d0ddff5ffee89a6bb9f29b64cd865411137b14
        with:
          input: rendered.yaml
          format: template
          template: template/sarif.tpl
          output: kubesec-results.sarif
          exit-code: "0"

      - name: Upload Kubesec scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: kubesec-results.sarif
