name: Lint Helm Chart

on:
  push:
    branches: [ "main", "gh-pages" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '40 5 * * 2'

jobs:
  lint:
    name: Helm Lint
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.15.2

      - name: Build Helm dependencies
        run: |
          helm dependency build chart/f7t4jhub

      # Render chart into a single yaml file
      - name: Render Helm chart
        run: |
          mkdir ci
          cd ci
          cp ../chart/Chart.yaml ../chart/values.yaml .
          cp -r ../chart/f7t4jhub .
          helm dependency build

      - name: Lint
        run: |
          helm lint
