name: Release Helm Chart

on:
  push:
    tags:
      - 'chart-v*'
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.14.3

    - name: Build Helm dependencies
      run: helm dependency build chart/

    - name: Package Helm chart
      run: |
        helm package chart/
        rm -rf chart/Chart.lock chart/charts/
        mkdir gh_
        mv *.tgz gh_

    - name: Push to gh-pages branch
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git fetch origin gh-pages:gh-pages
        git checkout gh-pages
        helm repo index . --url https://eth-cscs.github.io/firecrestspawner --merge index.yaml
        mv gh_/*tgz .
        git add *.tgz index.yaml
        git commit -m "Update Helm repo"
        git push origin gh-pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
